# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kelvin Arellano Portfolio Site
email: email@kelvin-arellano.com
description: This is a site dedicated showing my own growth as a developer and showcase my projects.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "kelvin-arellano.net" # the base hostname & protocol for your site
github_username:  kelvin-arellano

# Build settings
markdown: kramdown
